# Generated by Django 6.0.2 on 2026-02-24 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ministries.ministry'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'status'], name='members_mem_church__a10b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'join_date'], name='members_mem_church__b7ca30_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'ministry'], name='members_mem_church__ea34e7_idx'),
        ),
    ]
