# Generated by Django 6.0.2 on 2026-02-24 03:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('service_type', models.CharField(choices=[('SUNDAY', 'Sunday Service'), ('MIDWEEK', 'Midweek Service'), ('SPECIAL', 'Special Event')], default='SUNDAY', max_length=20)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance_attendance',
            },
        ),
    ]
