# Generated by Django 6.0.2 on 2026-02-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='service_notes',
            field=models.CharField(blank=True, help_text="Descripción cuando el tipo es 'Otro'", max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='service_type',
            field=models.CharField(choices=[('DOMINGO_ESCUELA', 'Domingo - Escuela dominical'), ('MARTES_ORACION', 'Martes - De oración'), ('JUEVES_CLAMOR', 'Jueves - Clamor y adoración'), ('MIERCOLES_AYUNO', 'Miércoles - Ayuno'), ('SABADO_AYUNO', 'Sábado - Ayuno'), ('OTRO', 'Otro (escribir)')], default='DOMINGO_ESCUELA', max_length=30),
        ),
    ]
